# TypeProf 0.21.7

# Classes
module Toyrobo
  module AST
    class Command
      attr_reader value: ::String
      attr_accessor params: Array[Num | String]
      def initialize: (untyped value, untyped `type`) -> void
    end
  end
end
