---
name: ast
version: '2.4'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 965029a810c265f39b2b85f8c0edc160e5275e3d
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
