# TypeProf 0.21.7

# Classes
module Toyrobo
  class CommandParser
    @input: Array[String]
    @tokens: Array[CommandParsers::Token]

    def initialize: (String input_string) -> void
    def tokenize: -> Array[CommandParsers::Token]
    def tokens: -> Array[CommandParsers::Token]
  end
end
