# TypeProf 0.21.7

# Classes
module Toyrobo
  class Parser
    @tokens: Array[CommandParsers::Token]
    @nodes: Array[untyped]

    def initialize: (Array[CommandParsers::Token] tokens) -> void
    def run: -> untyped
  end
end
