# TypeProf 0.21.7

# Classes
module Toyrobo
  class Robot
    ORIENTATIONS: ["north", "east", "south", "west"]
    ORIENTATION_RANGES: Hash[String, Integer]
    @plane: untyped
    @x_position: Integer
    @y_position: Integer

    attr_reader orientation: String
    def initialize: (untyped plane) -> void
    def current_position: -> {x_position: Integer, y_position: Integer, orientation: String}
    def orientation=: (String val) -> {x_position: Integer, y_position: Integer, orientation: String}
    def place: (Integer x_coor, Integer y_coor, String direction) -> {x_position: Integer, y_position: Integer, orientation: String}
    def robot: -> String
    def move: -> {x_position: Integer, y_position: Integer, orientation: String}
    def left: -> String
    def right: -> String
    def turn: (Integer numeric_direction) -> String
  end
end
