# TypeProf 0.21.7

# Classes
module Toyrobo
  class Robot
    ORIENTATIONS: [String, String, String, String]
    @plane: Table
    @x_position: Integer
    @y_position: Integer

    attr_reader orientation: String
    def initialize: (Table plane) -> void
    def current_position: -> {x_position: Integer, y_position: Integer, orientation: String}
    def orientation=: (String val) -> String
    def place: (Integer x_coor, Integer y_coor, String direction) -> untyped
    def robot: -> String
    def move: -> nil
    def left: -> String
    def right: -> String
    def turn: (Integer numeric_direction) -> String
  end
end
