# TypeProf 0.21.7

# Classes
module Toyrobo
  class Runner
    @robot: Toyrobo::Robot
    @filename: String
    @tokens: Array[Toyrobo::Lexers::Token]
    @parser: Toyrobo::Parser
    @interpreter: Toyrobo::Interpreter

    def initialize: -> void
    def run: -> untyped

    private
    def parser: -> Toyrobo::Parser
    def interpreter: -> Toyrobo::Interpreter
  end
end
