# TypeProf 0.21.7

# Classes
module Toyrobo
  class Table
    attr_reader store: Array[Array[Integer]]
    def initialize: (?Integer height, ?Integer width) -> void
    def get: (Integer x_coor, Integer y_coor) -> Integer?
  end
end
