# TypeProf 0.21.7

# Classes
module Toyrobo
  module CommandParsers
    class Token
      COMMANDS: [String, String, String, String, String]

      attr_accessor type: Symbol?
      attr_accessor text: String?
      attr_accessor args: untyped
      def initialize: (?Symbol `type`, ?String text) -> void
    end
  end
end
