# TypeProf 0.21.7

# Classes
module Toyrobo
  module CommandParsers
    class Token
      COMMANDS: Hash[Symbol, Symbol]
      TYPES: Hash[Symbol, Symbol]

      attr_accessor type: Symbol
      attr_accessor text: String
      attr_accessor args: untyped
      def initialize: (Symbol, String) -> void
    end
  end
end
